version: "3.8"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
  backend:
    build: 
      context: ./node-backend
      dockerfile: Dockerfile
    expose:
      - "5000"
  bot:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8080"
      - "80"
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "80"