version: "3.8"
services:
  backend:
    build: 
      context: ./node-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  bot:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "80:80"
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"